name: Chaos Engineering

on:
  schedule:
    # Run every day at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  chaos-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 9

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run chaos deployment test
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: ./scripts/chaos-deployment-test.sh

    - name: Alert on chaos failure
      if: failure()
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: failure
        text: '🔥 Chaos test failed for fact.rip - rollback may be compromised!'

    - name: Run drift detection after chaos
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: ./scripts/detect-netlify-drift.sh

    - name: Validate production after chaos
      run: |
        PROD_URL=$(cat config/deployment.json | jq -r '.netlify.productionUrl')
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$PROD_URL")
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "❌ Production site not responding correctly after chaos test!"
          exit 1
        fi
        echo "✅ Production site verified after chaos test"